# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GRADLEW: 'gradlew{{if eq OS "windows"}}.bat{{end}}'

tasks:
  lint:
    desc: Lint
    cmds:
      - prettier --check .
      - yamllint -c .github/yamllint.yaml .
      - actionlint -shellcheck="-e SC2129"
      - shellcheck .github/scripts/prepare.sh

  format:
    desc: Format
    aliases: [prettier, prettier:write]
    cmds:
      - prettier --write .

  compile:
    desc: Compile Kotlin
    cmd: "{{.GRADLEW}} :app:compileDebugKotlin"

  debug:
    desc: Build Debug (recommended android studio)
    cmd: "{{.GRADLEW}} assembleDebug {{.CLI_ARGS}}"

  release:
    desc: Build Release APK
    cmd: "{{.GRADLEW}} assembleRelease {{.CLI_ARGS}}"

  bundle:
    desc: Build Android App Bundle
    cmd: "{{.GRADLEW}} bundleRelease {{.CLI_ARGS}}"

  gradle-status:
    desc: Gradle daemon status
    cmd: "{{.GRADLEW}} --status"

  gradle-stop:
    desc: Stop Gradle daemons
    cmd: "{{.GRADLEW}} --stop"
