name: "Release"

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  file: app-release-unsigned.apk
  path: app/build/outputs/apk/release
  key_name: my-key
  key_file: release.keystore
  tools_path: /usr/local/lib/android/sdk/build-tools/36.0.0

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Set Tools Path"
        if: ${{ !github.event.act }}
        run: |
          echo "${{ env.tools_path }}" >> "$GITHUB_PATH"

      - name: "Debug Tools"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          echo "::group::PATH"
          echo ${PATH}
          echo "::endgroup::"

          echo "::group::ls env.tools_path"
          ls -lAh ${{ env.tools_path }}/
          echo "::endgroup::"

          echo "--------------------"
          which keytool
          which zipalign
          which apksigner

      - name: "Update Version"
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ github.ref_name }}

      - name: "Debug Version"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          cat "app/build.gradle.kts"

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          #cache: "gradle"

      - name: "Set Gradle Executable"
        run: chmod +x ./gradlew

      - name: "Gradlew Assemble"
        run: ./gradlew assembleRelease

      - name: "Debug Build"
        continue-on-error: true
        run: |
          echo "ref: ${{ github.ref }}"
          echo "name: ${{ github.repository_owner }}-release"
          echo "dir: ${{ env.path }}"
          echo "glob: ${{ env.path }}/*.apk"
          ls -lAh ${{ env.path }}

      - name: "Align APK"
        run: |
          mv "${{ env.path }}/${{ env.file }}" "${{ env.path }}/${{ env.file }}.original"
          zipalign -v 4 "${{ env.path }}/${{ env.file }}.original" "${{ env.path }}/${{ env.file }}"
          rm "${{ env.path }}/${{ env.file }}.original"

      - name: "Decode Keystore"
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.key_file }}

      - name: "Debug Keystore"
        continue-on-error: true
        run: |
          ls -lAh ${{ env.path }}

          stat ${{ env.key_file }}
          keytool -list -keystore ${{ env.key_file }}

      - name: "Sign APK"
        run: |
          apksigner sign --ks ${{ env.key_file }} \
            --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASS }} \
            --ks-key-alias "${{ env.key_name }}" \
            "${{ env.path }}/${{ env.file }}"

      - name: "Verify Signature"
        run: |
          apksigner verify --verbose "${{ env.path }}/${{ env.file }}"

      - name: "Upload Artifacts"
        if: ${{ !github.event.act }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_owner }}-release
          path: ${{ env.path }}

      - name: "Upload to Release"
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.path }}/${{ env.path }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "VirusTotal"
        uses: cssnr/virustotal-action@v1
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}

      - name: "Update Release Notes Action"
        uses: smashedr/update-release-notes-action@master
        continue-on-error: true

      - name: "Send Failure Notification"
        if: ${{ failure() && github.event_name == 'release' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
